### ISSUE TITLE
3.5.0 Release checklist

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#345]
- [x] Fix people that do not load / index (e.g., 30022139)
- [x] Fix #346
- [x] Fix #341 
- [x] Fix institutions without sigla (not opening in show?)
- [x] Pretty truncate catalogue.description (to 60?)
- [x] Guidelines are missing
- [x] Check IT  translations in Auth Files
- [ ] Check FR  translations in Auth Files
- [x] remove &lt and &gt, #349 
- [x] Verify modification status in the editor #181
- [x] Make sure data imports cleanly #350
- [x] Make `autocomplete_extra` fields higlighted when new entry is created
- [x] Subfield Relator codes should be only a normal list, without disabled text and without cascade update
- [x] Add filters for wf_status and record_type in source list
- [x] Fix #354 (for @HirschSt )

**Comment by xhero** [comment]
People that do not load is only the ones that had the missing 670? if so it was fixed in the last export

**Comment by xhero** [comment]
Institutions without sigla seem to work in the latest dataset (i.e. 63069)

**Comment by xhero** [comment]
I did a small fix that fixed Basic Functions, Guidelines seem to work for me?
